services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
       - chroma
    networks:
      - app-network
    restart: on-failure

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chroma_db:/data
    ports:
      - "8765:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
